version: "3.8"

services:
  autonode:
    build: .
    user: "${CURRENT_UID}:${CURRENT_GID}"
    group_add:
      - "${DOCKER_GID}"
    container_name: autonode
    restart: always
    env_file:
      - .env
    volumes:
      - ..:/src
      # ^ ^ ^ Checkpoint manager (SQLite)
      - ${HOST_DATA_ROOT}:/data
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /src/autonode
    environment:
      - PYTHONPATH=/src/autonode
      - SESSION_DIR=/src/autonode_docker
      - REPOS_ROOT=/src
      - DATA_ROOT=/data
      - DATA_DB_PATH=/data/autonode.db
      - HOST_PROJECTS_ROOT=${HOST_PROJECTS_ROOT}
      - HOST_DATA_ROOT=${HOST_DATA_ROOT}
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL}
      - GIT_COMMITTER_NAME=${GIT_AUTHOR_NAME}
      - GIT_COMMITTER_EMAIL=${GIT_AUTHOR_EMAIL}
    ports:
      - 8000:8000
    networks:
      - autonode-network

  appsmith:
    image: index.docker.io/appsmith/appsmith-ce:latest
    container_name: appsmith
    restart: always
    ports:
      - 8080:80
    volumes:
      - ${HOST_DATA_ROOT}/appsmith:/appsmith-stacks
    networks:
      - autonode-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: always
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "appsmith:80"
      - "--url=deltaic-dicastic-zayn.ngrok-free.dev"
    networks:
      - autonode-network
    depends_on:
      - appsmith

networks:
  autonode-network:
    driver: bridge
